### ISSUE TITLE
Cutoff for orfrating value and the forest score

### ISSUE THREAD

**Issue by xiaolichen0** [alexfields/ORF-RATER#7]
Hello Dr. Fields,

Thanks for the contribution of the software! It is much easier to run than other ORF finding tools

I was wondering which values I can use to decide the confidence of the new ORFs, the orfrating value or the forest scores. Is there a good cutoff for orfrating value and the forest score for the novel ORFs? Any help will be appreciated. Thanks in advance!

**Comment by alexfields** [comment]
Thanks for the kind words! I'm happy to hear you got it working.

The best value to use is the orfrating, which should be a little bit more reliable than the forest score. The cutoff to use depends on what you are trying to do. I usually use >0.8 for "high-confidence", but sometimes go down to 0.7 for a broader set, and I used a really broad set with a cutoff of 0.5 when cross-referencing mass spectrometry. I like to look in IGV at ORFs with different orfrating values to see which ones look believable. You can also plot the fraction AUG for different score ranges as an independent indicator.

I hope this helps. Feel free to reopen if you have additional questions.
