### ISSUE TITLE
Evaluate the likelihood that ORFs were protein coding

### ISSUE THREAD

**Issue by xiaolichen0** [alexfields/ORF-RATER#8]
Hello Dr. Fields,

Thank you so much for the explanation on cutoffs. I noticed you used PhyloCSF to evaluate the likelihood that ORFs were protein coding. I followed this idea and download the mm10 Multiz Align (Multiz60way) table (maf format) from the UCSC table browser. When I tried to extract the multiple alignment of new ORFs found by ORF-RATER, most of them were "NNNNN...". I was wondering if you used a more comprehensive maf file, or if you have a better way to evaluate this likelihood now.

Best Regards,
Xiaoli

**Comment by alexfields** [comment]
I used the same MAFs, but wrote some code to exclude "NNNNN..." sequences from other species. I also restricted to mammalian genomes, and I restricted to genomes that were in their second release or higher. But yes, it's impossible to find a valid alignment for many of the ORFs, and I don't have any better way to evaluate protein-coding sequence conservation.
