### ISSUE TITLE
Quantify result is a small subset of ORFs searching result

### ISSUE THREAD

**Issue by xiaolichen0** [alexfields/ORF-RATER#9]
Hi Dr. Fields,

Thanks a lot for the quick response! I used quantify_orfs.py after running rate_regression_output.py, and found the quant.csv is only a small subset of the orfratings.csv. I was wondering why the quantify_orfs.py filters out many ORFs. 

Best Regards,
Xiaoli

**Comment by alexfields** [comment]
By default, quantify_orfs.py only quantifies ORFs that received an orfrating of at least 0.8. You can adjust this using the `--minrating` parameter. The program also blocks out regions around the start and stop codons (`--startmask` and `--stopmask`), so ORFs that are too short do not get quantified. You can also set an explicit minimum length threshold using `--minlen`.
